# python srp03UiIndiciPane.py

from PyQt5.QtCore    import pyqtSlot
from PyQt5.QtGui     import QFont
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QVBoxLayout, QScrollArea, QFormLayout, QGroupBox, QComboBox
from PyQt5.QtWidgets import QLabel, QPushButton

class UiIndiciPanel(QWidget):



    def __init__(self, parent):
        QWidget.__init__(self)
        self.CntrPane = parent
        self.PaneIdx = 2

        def set_indici_item_text(indici_object):
            indici_object.setItemText(0, "Non rilevato")
            indici_object.setItemText(1, "Assente")
            indici_object.setItemText(2, "Presente")

        Font = QFont()
        Font.setPointSize(14)

        title_lbl = QLabel("INDICI")
        title_lbl_2 = QLabel("FATTORI DI RISCHIO DISTALI")
        label_1 = QLabel("1. Povertà cronica")
        label_2 = QLabel("2. Basso livello di istruzione")
        label_3 = QLabel("3. Giovane età della madre")







        indici_1 = QComboBox()
        indici_2 = QComboBox()
        indici_3 = QComboBox()

        set_indici_item_text(indici_1)
        set_indici_item_text(indici_2)
        set_indici_item_text(indici_3)










        Base = QVBoxLayout()
        Scroll = QScrollArea()
        Form = QFormLayout()

        Base.addWidget(title_lbl)
        Base.addWidget(Scroll)
        Scroll.setLayout(Form)
        Form.addRow(title_lbl_2)
        Form.addRow(label_1, indici_1)
        Form.addRow(label_2, indici_2)
        Form.addRow(label_3, indici_3)


        self.setLayout(Base)


        self.setLayout(Base)




    @pyqtSlot()
    def NextPane(self):
        NextIdx = self.PaneIdx + 1
        self.CntrPane.Panes.setCurrentIndex(NextIdx)


'''
        self.setFocusPolicy(Qt.TabFocus)
        self.centralwidget = QWidget(self)
        self.risultati_indici = QPushButton(self.centralwidget)
        self.risultati_indici.setGeometry(470, 530, 91, 23)

        self.risultati_indici.clicked.connect(self.indici_data)
        self.risultati_indici.clicked.connect(self.chiudi)

        palette = QPalette()
        brush = QBrush(QColor(0, 255, 127))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(240, 240, 240))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.risultati_indici.setPalette(palette)
        self.risultati_indici.setCursor(QCursor(Qt.ArrowCursor))
        self.reset_indici = QPushButton(self.centralwidget)
        self.reset_indici.setGeometry(570, 530, 91, 23)
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(200, 10, 521, 71)

        # There are many fonts, you should group them

        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(129, 89, 531, 401)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(0, 0, 512, 1169)
        self.formLayout_3 = QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_3.setContentsMargins(-1, -1, 15, -1)
        self.formLayout_2 = QFormLayout()
        self.formLayout_3.setLayout(4, QFormLayout.LabelRole, self.formLayout_2)
        self.label_45 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.formLayout_3.setWidget(6, QFormLayout.LabelRole, self.label_45)
        self.label_44 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(7, QFormLayout.LabelRole, self.label_44)
        self.indici_1 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_1.addItem("")
        self.indici_1.addItem("")
        self.indici_1.addItem("")
        self.formLayout_3.setWidget(7, QFormLayout.FieldRole, self.indici_1)
        self.label_43 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(8, QFormLayout.LabelRole, self.label_43)
        self.label_42 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(9, QFormLayout.LabelRole, self.label_42)
        self.label_41 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(10, QFormLayout.LabelRole, self.label_41)
        self.label_40 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(11, QFormLayout.LabelRole, self.label_40)
        self.label_39 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(12, QFormLayout.LabelRole, self.label_39)
        self.label_38 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(13, QFormLayout.LabelRole, self.label_38)
        self.label_37 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(14, QFormLayout.LabelRole, self.label_37)
        self.label_36 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(15, QFormLayout.LabelRole, self.label_36)
        self.label_35 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(16, QFormLayout.LabelRole, self.label_35)
        self.label_34 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(17, QFormLayout.LabelRole, self.label_34)
        self.label_33 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.formLayout_3.setWidget(18, QFormLayout.LabelRole, self.label_33)
        self.label_32 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.label_32.setFont(font)
        self.formLayout_3.setWidget(19, QFormLayout.LabelRole, self.label_32)
        self.label_31 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(20, QFormLayout.LabelRole, self.label_31)
        self.label_30 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(21, QFormLayout.LabelRole, self.label_30)
        self.label_29 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(22, QFormLayout.LabelRole, self.label_29)
        self.label_28 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(23, QFormLayout.LabelRole, self.label_28)
        self.label_27 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(24, QFormLayout.LabelRole, self.label_27)
        self.label_26 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(25, QFormLayout.LabelRole, self.label_26)
        self.label_25 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(26, QFormLayout.LabelRole, self.label_25)
        self.label_24 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(27, QFormLayout.LabelRole, self.label_24)
        self.label_23 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(28, QFormLayout.LabelRole, self.label_23)
        self.label_22 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.label_22.setFont(font)
        self.formLayout_3.setWidget(29, QFormLayout.LabelRole, self.label_22)
        self.label_21 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(30, QFormLayout.LabelRole, self.label_21)
        self.label_20 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(31, QFormLayout.LabelRole, self.label_20)
        self.label_19 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(32, QFormLayout.LabelRole, self.label_19)
        self.label_18 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.label_18.setFont(font)
        self.formLayout_3.setWidget(33, QFormLayout.LabelRole, self.label_18)
        self.label_17 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(34, QFormLayout.LabelRole, self.label_17)
        self.label_16 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(35, QFormLayout.LabelRole, self.label_16)
        self.label_15 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.formLayout_3.setWidget(36, QFormLayout.LabelRole, self.label_15)
        self.label_14 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(38, QFormLayout.LabelRole, self.label_14)
        self.label_13 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(39, QFormLayout.LabelRole, self.label_13)
        self.label_12 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(40, QFormLayout.LabelRole, self.label_12)
        self.label_11 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(41, QFormLayout.LabelRole, self.label_11)
        self.label_10 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(42, QFormLayout.LabelRole, self.label_10)
        self.label_9 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(43, QFormLayout.LabelRole, self.label_9)
        self.label_8 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(44, QFormLayout.LabelRole, self.label_8)
        self.label_7 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.label_7.setFont(font)
        self.formLayout_3.setWidget(45, QFormLayout.LabelRole, self.label_7)
        self.label_6 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(46, QFormLayout.LabelRole, self.label_6)
        self.label_5 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(47, QFormLayout.LabelRole, self.label_5)
        self.label_4 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(48, QFormLayout.LabelRole, self.label_4)
        self.label_3 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.label_3.setFont(font)
        self.formLayout_3.setWidget(49, QFormLayout.LabelRole, self.label_3)
        self.label_2 = QLabel(self.scrollAreaWidgetContents)
        self.formLayout_3.setWidget(50, QFormLayout.LabelRole, self.label_2)
        self.label_46 = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.label_46.setFont(font)
        self.formLayout_3.setWidget(37, QFormLayout.LabelRole, self.label_46)
        self.indici_2 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_2.addItem("")
        self.indici_2.addItem("")
        self.indici_2.addItem("")
        self.formLayout_3.setWidget(8, QFormLayout.FieldRole, self.indici_2)
        self.indici_3 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_3.addItem("")
        self.indici_3.addItem("")
        self.indici_3.addItem("")
        self.formLayout_3.setWidget(9, QFormLayout.FieldRole, self.indici_3)
        self.indici_4 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_4.addItem("")
        self.indici_4.addItem("")
        self.indici_4.addItem("")
        self.formLayout_3.setWidget(10, QFormLayout.FieldRole, self.indici_4)
        self.indici_5 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_5.addItem("")
        self.indici_5.addItem("")
        self.indici_5.addItem("")
        self.formLayout_3.setWidget(11, QFormLayout.FieldRole, self.indici_5)
        self.indici_6 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_6.addItem("")
        self.indici_6.addItem("")
        self.indici_6.addItem("")
        self.formLayout_3.setWidget(12, QFormLayout.FieldRole, self.indici_6)
        self.indici_7 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_7.addItem("")
        self.indici_7.addItem("")
        self.indici_7.addItem("")
        self.formLayout_3.setWidget(13, QFormLayout.FieldRole, self.indici_7)
        self.indici_8 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_8.addItem("")
        self.indici_8.addItem("")
        self.indici_8.addItem("")
        self.formLayout_3.setWidget(14, QFormLayout.FieldRole, self.indici_8)
        self.indici_9 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_9.addItem("")
        self.indici_9.addItem("")
        self.indici_9.addItem("")
        self.formLayout_3.setWidget(15, QFormLayout.FieldRole, self.indici_9)
        self.indici_10 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_10.addItem("")
        self.indici_10.addItem("")
        self.indici_10.addItem("")
        self.formLayout_3.setWidget(16, QFormLayout.FieldRole, self.indici_10)
        self.indici_11 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_11.addItem("")
        self.indici_11.addItem("")
        self.indici_11.addItem("")
        self.formLayout_3.setWidget(17, QFormLayout.FieldRole, self.indici_11)
        self.indici_12 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_12.addItem("")
        self.indici_12.addItem("")
        self.indici_12.addItem("")
        self.formLayout_3.setWidget(20, QFormLayout.FieldRole, self.indici_12)
        self.indici_13 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_13.addItem("")
        self.indici_13.addItem("")
        self.indici_13.addItem("")
        self.formLayout_3.setWidget(21, QFormLayout.FieldRole, self.indici_13)
        self.indici_14 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_14.addItem("")
        self.indici_14.addItem("")
        self.indici_14.addItem("")
        self.formLayout_3.setWidget(22, QFormLayout.FieldRole, self.indici_14)
        self.indici_15 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_15.addItem("")
        self.indici_15.addItem("")
        self.indici_15.addItem("")
        self.formLayout_3.setWidget(23, QFormLayout.FieldRole, self.indici_15)
        self.indici_16 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_16.addItem("")
        self.indici_16.addItem("")
        self.indici_16.addItem("")
        self.formLayout_3.setWidget(24, QFormLayout.FieldRole, self.indici_16)
        self.indici_17 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_17.addItem("")
        self.indici_17.addItem("")
        self.indici_17.addItem("")
        self.formLayout_3.setWidget(25, QFormLayout.FieldRole, self.indici_17)
        self.indici_18 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_18.addItem("")
        self.indici_18.addItem("")
        self.indici_18.addItem("")
        self.formLayout_3.setWidget(26, QFormLayout.FieldRole, self.indici_18)
        self.indici_19 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_19.addItem("")
        self.indici_19.addItem("")
        self.indici_19.addItem("")
        self.formLayout_3.setWidget(27, QFormLayout.FieldRole, self.indici_19)
        self.indici_20 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_20.addItem("")
        self.indici_20.addItem("")
        self.indici_20.addItem("")
        self.formLayout_3.setWidget(28, QFormLayout.FieldRole, self.indici_20)
        self.indici_21 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_21.addItem("")
        self.indici_21.addItem("")
        self.indici_21.addItem("")
        self.formLayout_3.setWidget(30, QFormLayout.FieldRole, self.indici_21)
        self.indici_22 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_22.addItem("")
        self.indici_22.addItem("")
        self.indici_22.addItem("")
        self.formLayout_3.setWidget(31, QFormLayout.FieldRole, self.indici_22)
        self.indici_23 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_23.addItem("")
        self.indici_23.addItem("")
        self.indici_23.addItem("")
        self.formLayout_3.setWidget(32, QFormLayout.FieldRole, self.indici_23)
        self.indici_25 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_25.addItem("")
        self.indici_25.addItem("")
        self.indici_25.addItem("")
        self.formLayout_3.setWidget(34, QFormLayout.FieldRole, self.indici_25)
        self.indici_24 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_24.addItem("")
        self.indici_24.addItem("")
        self.indici_24.addItem("")
        self.formLayout_3.setWidget(35, QFormLayout.FieldRole, self.indici_24)
        self.indici_26 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_26.addItem("")
        self.indici_26.addItem("")
        self.indici_26.addItem("")
        self.formLayout_3.setWidget(38, QFormLayout.FieldRole, self.indici_26)
        self.indici_27 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_27.addItem("")
        self.indici_27.addItem("")
        self.indici_27.addItem("")
        self.formLayout_3.setWidget(39, QFormLayout.FieldRole, self.indici_27)
        self.indici_28 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_28.addItem("")
        self.indici_28.addItem("")
        self.indici_28.addItem("")
        self.formLayout_3.setWidget(40, QFormLayout.FieldRole, self.indici_28)
        self.indici_29 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_29.addItem("")
        self.indici_29.addItem("")
        self.indici_29.addItem("")
        self.formLayout_3.setWidget(41, QFormLayout.FieldRole, self.indici_29)
        self.indici_30 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_30.addItem("")
        self.indici_30.addItem("")
        self.indici_30.addItem("")
        self.formLayout_3.setWidget(42, QFormLayout.FieldRole, self.indici_30)
        self.indici_31 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_31.addItem("")
        self.indici_31.addItem("")
        self.indici_31.addItem("")
        self.formLayout_3.setWidget(43, QFormLayout.FieldRole, self.indici_31)
        self.indici_32 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_32.addItem("")
        self.indici_32.addItem("")
        self.indici_32.addItem("")
        self.formLayout_3.setWidget(44, QFormLayout.FieldRole, self.indici_32)
        self.indici_33 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_33.addItem("")
        self.indici_33.addItem("")
        self.indici_33.addItem("")
        self.formLayout_3.setWidget(46, QFormLayout.FieldRole, self.indici_33)
        self.indici_34 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_34.addItem("")
        self.indici_34.addItem("")
        self.indici_34.addItem("")
        self.formLayout_3.setWidget(47, QFormLayout.FieldRole, self.indici_34)
        self.indici_35 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_35.addItem("")
        self.indici_35.addItem("")
        self.indici_35.addItem("")
        self.formLayout_3.setWidget(48, QFormLayout.FieldRole, self.indici_35)
        self.indici_36 = QComboBox(self.scrollAreaWidgetContents)
        self.indici_36.addItem("")
        self.indici_36.addItem("")
        self.indici_36.addItem("")
        self.formLayout_3.setWidget(50, QFormLayout.FieldRole, self.indici_36)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(self)
        self.setStatusBar(self.statusbar)

        self.setWindowTitle("S.R.P.")
        self.risultati_indici.setText("RISULTATI")
        self.reset_indici.setText("Reset")
        self.label.setText("INDICI: Fattori di rischio e protettivi")
        self.label_45.setText("FATTORI DI RISCHIO DISTALI")
        self.label_44.setText("1. Povertà cronica")
        self.indici_1.setItemText(0, "Non rilevato")
        self.indici_1.setItemText(1, "Assente")
        self.indici_1.setItemText(2, "Presente")
        self.label_43.setText("2. Basso livello di istruzione")
        self.label_42.setText("3. Giovane età della madre")
        self.label_41.setText("4. Carenza di relazioni interpersonali")
        self.label_40.setText("5. Carenza di reti e di integrazione sociale")
        self.label_39.setText("6. Famiglia monoparentale")
        self.label_38.setText("7. Esperienze di rifiuto, violenza, abuso subite nell\'infanzia")
        self.label_37.setText("8. Sfiducia verso le norme sociali e le istituzioni")
        self.label_36.setText("9. Accettazione della violenza e delle punizioni come pratiche educative")
        self.label_35.setText("10. Accettazione della pornografia infantile")
        self.label_34.setText("11. Scarse conoscenze e disinteresse per lo sviluppo del bambino")
        self.label_33.setText("FATTORI PROSSIMALI DI RISCHIO / AMPLIFICAZIONE RISCHIO")
        self.label_32.setText("FATTORI INDIVIDUALI")
        self.label_31.setText("12. Psicopatologia genitori")
        self.label_30.setText("13. Devianza sociale genitori")
        self.label_29.setText("14. Abuso sostanze")
        self.label_28.setText("15. Debole/assente capacità di assunzione responsabilità")
        self.label_27.setText("16. Sindrome da risarcimento")
        self.label_26.setText("17. Distorsione emozioni / capacità empatiche")
        self.label_25.setText("18. Impulsività")
        self.label_24.setText("19. Scarsa tolleranza frustrazioni")
        self.label_23.setText("20. Ansia da separazione")
        self.label_22.setText("FATTORI FAMILIARI")
        self.label_21.setText("21. Gravidanza/maternità non desiderate")
        self.label_20.setText("22. Relazioni difficili con famiglia d\'origine del partner")
        self.label_19.setText("23. Conflitti di coppia / violenza domestica")
        self.label_18.setText("CARATTERISTICHE DEL BAMBINO")
        self.label_17.setText("24. Malattie fisiche/disturbi alla nascita")
        self.label_16.setText("25. Temperamento difficile")
        self.label_15.setText("FATTORI PROSSIMALI PROTETTIVI / RIDUZIONE RISCHIO")
        self.label_14.setText("26. Sentimenti di inadeguatezza per dipendenza dai servizi")
        self.label_13.setText("27. Rielaborazione rifiuto/violenza subiti nell\'infanzia")
        self.label_12.setText("28. Capacità empatiche")
        self.label_11.setText("29. Capacità di assunzione di responsabilità")
        self.label_10.setText("30. Desiderio di migliorarsi")
        self.label_9.setText("31. Autonomia personale")
        self.label_8.setText("32. Buon livello di autostima")
        self.label_7.setText("FATTORI FAMILIARI")
        self.label_6.setText("33. Relazione attuale soddisfacente con almeno un membro fam. Origine")
        self.label_5.setText("34. Rete di supporto parentale / amicale")
        self.label_4.setText("35. Capacità di gestire i conflitti")
        self.label_3.setText("CARATTERISTICHE DEL BAMBINO")
        self.label_2.setText("36. Temperamento facile")
        self.label_46.setText("FATTORI INDIVIDUALI")
        self.indici_2.setItemText(0, "Non rilevato")
        self.indici_2.setItemText(1, "Assente")
        self.indici_2.setItemText(2, "Presente")
        self.indici_3.setItemText(0, "Non rilevato")
        self.indici_3.setItemText(1, "Assente")
        self.indici_3.setItemText(2, "Presente")
        self.indici_4.setItemText(0, "Non rilevato")
        self.indici_4.setItemText(1, "Assente")
        self.indici_4.setItemText(2, "Presente")
        self.indici_5.setItemText(0, "Non rilevato")
        self.indici_5.setItemText(1, "Assente")
        self.indici_5.setItemText(2, "Presente")
        self.indici_6.setItemText(0, "Non rilevato")
        self.indici_6.setItemText(1, "Assente")
        self.indici_6.setItemText(2, "Presente")
        self.indici_7.setItemText(0, "Non rilevato")
        self.indici_7.setItemText(1, "Assente")
        self.indici_7.setItemText(2, "Presente")
        self.indici_8.setItemText(0, "Non rilevato")
        self.indici_8.setItemText(1, "Assente")
        self.indici_8.setItemText(2, "Presente")
        self.indici_9.setItemText(0, "Non rilevato")
        self.indici_9.setItemText(1, "Assente")
        self.indici_9.setItemText(2, "Presente")
        self.indici_10.setItemText(0, "Non rilevato")
        self.indici_10.setItemText(1, "Assente")
        self.indici_10.setItemText(2, "Presente")
        self.indici_11.setItemText(0, "Non rilevato")
        self.indici_11.setItemText(1, "Assente")
        self.indici_11.setItemText(2, "Presente")
        self.indici_12.setItemText(0, "Non rilevato")
        self.indici_12.setItemText(1, "Assente")
        self.indici_12.setItemText(2, "Presente")
        self.indici_13.setItemText(0, "Non rilevato")
        self.indici_13.setItemText(1, "Assente")
        self.indici_13.setItemText(2, "Presente")
        self.indici_14.setItemText(0, "Non rilevato")
        self.indici_14.setItemText(1, "Assente")
        self.indici_14.setItemText(2, "Presente")
        self.indici_15.setItemText(0, "Non rilevato")
        self.indici_15.setItemText(1, "Assente")
        self.indici_15.setItemText(2, "Presente")
        self.indici_16.setItemText(0, "Non rilevato")
        self.indici_16.setItemText(1, "Assente")
        self.indici_16.setItemText(2, "Presente")
        self.indici_17.setItemText(0, "Non rilevato")
        self.indici_17.setItemText(1, "Assente")
        self.indici_17.setItemText(2, "Presente")
        self.indici_18.setItemText(0, "Non rilevato")
        self.indici_18.setItemText(1, "Assente")
        self.indici_18.setItemText(2, "Presente")
        self.indici_19.setItemText(0, "Non rilevato")
        self.indici_19.setItemText(1, "Assente")
        self.indici_19.setItemText(2, "Presente")
        self.indici_20.setItemText(0, "Non rilevato")
        self.indici_20.setItemText(1, "Assente")
        self.indici_20.setItemText(2, "Presente")
        self.indici_21.setItemText(0, "Non rilevato")
        self.indici_21.setItemText(1, "Assente")
        self.indici_21.setItemText(2, "Presente")
        self.indici_22.setItemText(0, "Non rilevato")
        self.indici_22.setItemText(1, "Assente")
        self.indici_22.setItemText(2, "Presente")
        self.indici_23.setItemText(0, "Non rilevato")
        self.indici_23.setItemText(1, "Assente")
        self.indici_23.setItemText(2, "Presente")
        self.indici_25.setItemText(0, "Non rilevato")
        self.indici_25.setItemText(1, "Assente")
        self.indici_25.setItemText(2, "Presente")
        self.indici_24.setItemText(0, "Non rilevato")
        self.indici_24.setItemText(1, "Assente")
        self.indici_24.setItemText(2, "Presente")
        self.indici_26.setItemText(0, "Non rilevato")
        self.indici_26.setItemText(1, "Assente")
        self.indici_26.setItemText(2, "Presente")
        self.indici_27.setItemText(0, "Non rilevato")
        self.indici_27.setItemText(1, "Assente")
        self.indici_27.setItemText(2, "Presente")
        self.indici_28.setItemText(0, "Non rilevato")
        self.indici_28.setItemText(1, "Assente")
        self.indici_28.setItemText(2, "Presente")
        self.indici_29.setItemText(0, "Non rilevato")
        self.indici_29.setItemText(1, "Assente")
        self.indici_29.setItemText(2, "Presente")
        self.indici_30.setItemText(0, "Non rilevato")
        self.indici_30.setItemText(1, "Assente")
        self.indici_30.setItemText(2, "Presente")
        self.indici_31.setItemText(0, "Non rilevato")
        self.indici_31.setItemText(1, "Assente")
        self.indici_31.setItemText(2, "Presente")
        self.indici_32.setItemText(0, "Non rilevato")
        self.indici_32.setItemText(1, "Assente")
        self.indici_32.setItemText(2, "Presente")
        self.indici_33.setItemText(0, "Non rilevato")
        self.indici_33.setItemText(1, "Assente")
        self.indici_33.setItemText(2, "Presente")
        self.indici_34.setItemText(0, "Non rilevato")
        self.indici_34.setItemText(1, "Assente")
        self.indici_34.setItemText(2, "Presente")
        self.indici_35.setItemText(0, "Non rilevato")
        self.indici_35.setItemText(1, "Assente")
        self.indici_35.setItemText(2, "Presente")
        self.indici_36.setItemText(0, "Non rilevato")
        self.indici_36.setItemText(1, "Assente")
        self.indici_36.setItemText(2, "Presente")

    def open(self):
        self.show()
    def indici_data(self):
        indiciData = [getattr(self, 'indici_{}'.format(i)).currentText() for i in range(1, 37)]
        return(indiciData)
    def chiudi(self):
        window4.show()
        self.close()
'''
